server:
  port: 8080
  servlet:
    context-path: /identity # http://localhost:8080/identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/identity_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
